<a href="https://colab.research.google.com/github/ithyr/ithyr.github.io/blob/main/ENVS_617_Assignment_1_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 1: Python and Pandas Introduction
Time to start coding! Respond to the prompts/questions below.

Add code blocks below each question using the `+ Code` button at the top of the doc, or above each cell.

Our future assignments will be end-to-end explorations of datasets, but this first assignment will be quick exercises to give you pracatice with foundational skills.

# Intro to `python` Exercises

### Part 1: Strings

1. Per tradition, we'll start with displaying the string `"Hello world"`. Assign the string `"Hello world"` to a variable called `greetings`, and display `greetings`.

In [1]:
greetings = "Hello world"
greetings

'Hello world'

2. You're a Beatles fan. Assign `"Paul McCartney"` to a new variable `artist`

In [6]:
artist = "Paul McCartney"
artist

'Paul McCartney'

In [7]:
artist = "Sir " + artist
artist

'Sir Paul McCartney'

3. Actually, he's "Sir Paul McCartney"...concatenate `"Sir "` to beginning of `artist` and reassign that to `artist` (overwrite). Display your results.

⚠️ Notice: What happens if you run the cell above a few times? This self referential statement is called a recursive statement. It can be a little dangerous in data science applications because it's so easy to run the cell multiple times in a row!

**To 'reset' the** `artist` **variable after running you question 3 code multiple times, go back and run your question 2 code, then run your questioin 3 code once.**

In the real world, generally, it'd be stategic to place your code for question 2 in the same cell as your code for question 3. That way, erroneous runs of a cell won't mess up your analysis

### Part 2: Python as a calculator

1. The circumference of the earth is 24,902 miles. There are 1609.34 meters per mile. Use `*` to convert the circumference of the earth from miles to kilometers. Store this in a new variable `earth_circ_km`

In [8]:
earth_circ_km = 24902*1.60934
earth_circ_km

40075.78468

2. When Greta Thunberg sailed to the UN Climate Summit in NY in 2019, she sailed 4,800km from the UK to NY. Use `/` to calculate what % of the earth's circumference Greta's trip was equivalent to. Store that in a new variable `greta_earth_circ_eq_km`

In [10]:
greta_earth_circ_eq_km = 4800/earth_circ_km * 100
greta_earth_circ_eq_km

11.977307589426845

### Part 3: Lists


We'll practice creating and manipulating lists

1. Create a list `ls` with 3 string elements in the following order: `"select"`, `"the"`, `"number"`.

In [11]:
ls = ["select", "the", "number"]
ls

['select', 'the', 'number']

2. Select the `"number"` element. Display the results.

In [12]:
ls[2]

'number'

### Part 4: Dictionaries
One common instance where we do (unfortunately) have to manually input data into a dictionary is when we need to create a custom mapping, say for a visualization.

1. Create a dictionary based the legend below. The first key should be "Temp Range", and the first value should be a list of the temperature ranges as strings. The second key should be "Color" and the second value should be a list of the colors (again as strings), in an order corresponding to the temperature ranges. Assign your dictionary to a variable and display the results.


![image.png]()

In [13]:
temp_color = {'Temp Range' : ['100+', '80-100', '60-80', '40-60', '20-40'], 'Color' : ['Purple', 'Red', 'Pink', 'Yellow', 'Blue']}
temp_color

{'Temp Range': ['100+', '80-100', '60-80', '40-60', '20-40'],
 'Color': ['Purple', 'Red', 'Pink', 'Yellow', 'Blue']}

# Intro to `pandas` Exercises

### Part 5: Reading in data

9 /10 times, we won't be inputting our data by hand, thankfully. Let's practice reading data in from external sources

1. For the rest of the exercises, we'll need to use `pandas`. Import `pandas` and call it `pd` (its standard alias). Note that in future this will be the first thing we do at the top of a notebook.

In [14]:
import numpy as np
import pandas as pd

2. The USGS publishes annual estimates of pestidice use in the continental US by county. The datasets on the subject are available [here.](https://water.usgs.gov/nawqa/pnsp/usage/maps/county-level/)

  Below is a link to the dataset from 2020 that covers pesticide use estimates between 2013 and 2017.

  ```
  https://www.sciencebase.gov/catalog/file/get/5e95c12282ce172707f2524e?f=__disk__62%2F83%2Fd3%2F6283d3501f1028b1ccc3976ea2e6de848bc2fef8
  ```

  Read the data into a dataframe `df`. Preview the first 10 rows of `df`. If you're having trouble reading in the data, start by downloading the file on your computer by pasting the URL into your browser (that will start downloading the .txt file!) Open the file in any text editor (TextEdit and Notepad are usually the defaults on Macs and PCs, respectively), and look at how the columns of data are separated.  (Hint, do you see commas separating fields?)

In [17]:
url = 'https://www.sciencebase.gov/catalog/file/get/5e95c12282ce172707f2524e?f=__disk__62%2F83%2Fd3%2F6283d3501f1028b1ccc3976ea2e6de848bc2fef8'
df = pd.read_csv(url, sep='\t')
df.head(10)

,COMPOUND,YEAR,STATE_FIPS_CODE,COUNTY_FIPS_CODE,EPEST_LOW_KG,EPEST_HIGH_KG
0,1-METHYL CYCLOPROPENE,2013,41,1,NaN,0.0
1,1-METHYL CYCLOPROPENE,2013,41,21,NaN,0.0
2,1-METHYL CYCLOPROPENE,2013,41,27,NaN,0.2
3,1-METHYL CYCLOPROPENE,2013,41,49,NaN,0.0
4,1-METHYL CYCLOPROPENE,2013,41,55,NaN,0.0
5,1-METHYL CYCLOPROPENE,2013,41,59,NaN,0.5
6,1-METHYL CYCLOPROPENE,2013,41,61,NaN,0.0
7,1-METHYL CYCLOPROPENE,2013,41,63,NaN,0.0
8,1-METHYL CYCLOPROPENE,2013,41,65,NaN,0.0
9,1-METHYL CYCLOPROPENE,2013,53,1,7.5,7.5

3. Check that the data was read in correctly using:

  *   `.info()`
  *   `.tail()`
  *   `.shape` - for practice :) This is redundant with `.info()`

  Take a moment to appreciate how much data we're working with!

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2004805 entries, 0 to 2004804
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   COMPOUND          object
 1   YEAR              int64
 2   STATE_FIPS_CODE   int64
 3   COUNTY_FIPS_CODE  int64
 4   EPEST_LOW_KG      float64
 5   EPEST_HIGH_KG     float64
dtypes: float64(2), int64(3), object(1)
memory usage: 91.8+ MB

In [19]:
df.tail()

,COMPOUND,YEAR,STATE_FIPS_CODE,COUNTY_FIPS_CODE,EPEST_LOW_KG,EPEST_HIGH_KG
2004800,ZOXAMIDE,2017,55,133,0.0,0.1
2004801,ZOXAMIDE,2017,55,135,28.2,28.2
2004802,ZOXAMIDE,2017,55,137,315.0,315.0
2004803,ZOXAMIDE,2017,55,139,0.1,3.2
2004804,ZOXAMIDE,2017,55,141,1.7,1.7

In [21]:
df.shape

(2004805, 6)

### Part 6: Data Context
When orienting to a new dataset, it is critical to understand where the data comes from, and what appropriate uses are.

1. Take a minute to read about this dataset from the USGS download site, linked below. Suppose we were interested in comparing total pesticide use in the entire continental US in 2016 vs. 2014. What might be a limitation of this data for that use?

  https://www.sciencebase.gov/catalog/item/5e95c12282ce172707f2524e

This dataset focuses on agricultural use of pesticides, rather than all uses of pesticides. While agricultural use is likely the largest component nationwide, there are likely counties where private pesticide use dominates (golf courses, suburbia, etc.), and this dataset misses that pesticide use.

More broadly, the description of the data clearly states these are estimates of county-level usage, and thus any national numbers would be an aggregation of these county estimates, which should be noted in any analysis of these data. In addition, not all datapoints have the same estimators – some only have low estimates while others only have high ones.

### Part 7: Column selection and column operations

1.  For practice, select the `YEAR`, `STATE_FIPS_CODE`, and `COUNTY_FIPS_CODE` columns in `df`. Do not store the results anywhere, just display the result.

In [23]:
df[['YEAR', 'STATE_FIPS_CODE', 'COUNTY_FIPS_CODE']]

         YEAR  STATE_FIPS_CODE  COUNTY_FIPS_CODE
0        2013               41                 1
1        2013               41                21
2        2013               41                27
3        2013               41                49
4        2013               41                55
...       ...              ...               ...
2004800  2017               55               133
2004801  2017               55               135
2004802  2017               55               137
2004803  2017               55               139
2004804  2017               55               141

[2004805 rows x 3 columns]

2. For practice, drop the `EPEST_HIGH_KG` column from `df`. Do not store the results anywhere, just display the result.

In [26]:
df.drop(columns ='EPEST_HIGH_KG')

,COMPOUND,YEAR,STATE_FIPS_CODE,COUNTY_FIPS_CODE,EPEST_LOW_KG
0,1-METHYL CYCLOPROPENE,2013,41,1,NaN
1,1-METHYL CYCLOPROPENE,2013,41,21,NaN
2,1-METHYL CYCLOPROPENE,2013,41,27,NaN
3,1-METHYL CYCLOPROPENE,2013,41,49,NaN
4,1-METHYL CYCLOPROPENE,2013,41,55,NaN
...,...,...,...,...,...
2004800,ZOXAMIDE,2017,55,133,0.0
2004801,ZOXAMIDE,2017,55,135,28.2
2004802,ZOXAMIDE,2017,55,137,315.0
2004803,ZOXAMIDE,2017,55,139,0.1
2004804,ZOXAMIDE,2017,55,141,1.7

3. Display the unique pesticide `COMPOUND` values included in this dataset.

In [27]:
df.COMPOUND.unique()

array(['1-METHYL CYCLOPROPENE', '2,4-D', '2,4-DB', '6-BENZYLADENINE',
       'ABAMECTIN', 'ABSCISIC ACID', 'ACEPHATE', 'ACEQUINOCYL',
       'ACETAMIPRID', 'ACETOCHLOR', 'ACIBENZOLAR', 'ACIFLUORFEN',
       'ALACHLOR', 'ALDICARB', 'ALLYL ISOTHIOCYANATE',
       'ALPHA CYPERMETHRIN', 'ALUMINUM PHOSPHIDE', 'AMETOCTRADIN',
       'AMETRYN', 'AMINOPYRALID', 'AMITROLE', 'ASPERGILLUS FLAVUS',
       'ASULAM', 'ATRAZINE', 'AUREOBASIDIUM PULLULANS', 'AVIGLYCINE',
       'AZADIRACHTIN', 'AZINPHOS-METHYL', 'AZOXYSTROBIN',
       'BACILLUS AMYLOLIQUEFACIEN', 'BACILLUS CEREUS', 'BACILLUS FIRMUS',
       'BACILLUS MYCOIDES', 'BACILLUS PUMILIS', 'BACILLUS SUBTILIS',
       'BACILLUS THURINGIENSIS', 'BACTERIOPHAGE', 'BEAUVERIA BASSIANA',
       'BENFLURALIN', 'BENOMYL', 'BENSULFURON', 'BENSULIDE', 'BENTAZONE',
       'BENZOVINDIFLUPYR', 'BICYCLOPYRONE', 'BIFENAZATE', 'BIFENTHRIN',
       'BISPYRIBAC', 'BLAD PROTEIN', 'BOSCALID', 'BROMACIL', 'BROMOXYNIL',
       'BUPROFEZIN', 'BURKHOLDERIA CEPACIA', 'BURKHOLDERIA SPP',
       'BUTRALIN', 'BUTYLATE', 'CALCIUM POLYSULFIDE', 'CAPTAN',
       'CARBARYL', 'CARBOPHENOTHION', 'CARBOXIN', 'CARFENTRAZONE-ETHYL',
       'CHENOPODIUM AMBROSIOIDES', 'CHINOMETHIONAT',
       'CHLORANTRANILIPROLE', 'CHLORETHOXYFOS', 'CHLORFENAPYR',
       'CHLORIMURON', 'CHLORMEQUAT', 'CHLORONEB', 'CHLOROPICRIN',
       'CHLOROTHALONIL', 'CHLORPROPHAM', 'CHLORPYRIFOS', 'CHLORSULFURON',
       'CHROMOBACTERIUM SUBTSUGAE', 'CINNAMALDEHYDE', 'CLETHODIM',
       'CLODINAFOP', 'CLOFENTEZINE', 'CLOMAZONE', 'CLOPYRALID',
       'CLORANSULAM-METHYL', 'CLOTHIANIDIN', 'CONIOTHYRIUM MINITANS',
       'COPPER', 'COPPER HYDROXIDE', 'COPPER OCTANOATE',
       'COPPER OXYCHLORIDE', 'COPPER OXYCHLORIDE S', 'COPPER SULFATE',
       'COPPER SULFATE TRIBASIC', 'CPPU', 'CRYOLITE', 'CUPROUS OXIDE',
       'CYANAMIDE', 'CYANTRANILIPROLE', 'CYAZOFAMID', 'CYCLANILIDE',
       'CYCLOATE', 'CYDIA POMONELLA', 'CYFLUFENAMID', 'CYFLUMETOFEN',
       'CYFLUTHRIN', 'CYHALOFOP', 'CYHALOTHRIN-GAMMA',
       'CYHALOTHRIN-LAMBDA', 'CYMOXANIL', 'CYPERMETHRIN', 'CYPROCONAZOLE',
       'CYPRODINIL', 'CYROMAZINE', 'CYTOKININ', 'DAMINOZIDE', 'DAZOMET',
       'DCPA', 'DECAN-1-OL', 'DELTAMETHRIN', 'DESMEDIPHAM', 'DIAZINON',
       'DICAMBA', 'DICHLOBENIL', 'DICHLOROPROPENE', 'DICHLORPROP',
       'DICLOFOP', 'DICLORAN', 'DICLOSULAM', 'DICOFOL', 'DICROTOPHOS',
       'DIENOCHLOR', 'DIETHATYL', 'DIFENOCONAZOLE', 'DIFLUBENZURON',
       'DIFLUFENZOPYR', 'DIMETHENAMID', 'DIMETHENAMID & DIMETHENAMID-P',
       'DIMETHENAMID-P', 'DIMETHOATE', 'DIMETHOMORPH',
       'DIMETHYL ARSINIC ACID', 'DIMETHYL DISULFIDE', 'DINOCAP',
       'DINOSEB', 'DINOTEFURAN', 'DIPHENAMID', 'DIQUAT', 'DISULFOTON',
       'DITHIOPYR', 'DIURON', 'DODINE', 'EMAMECTIN', 'ENDOSULFAN',
       'ENDOTHAL', 'EPN', 'EPTC', 'ESFENVALERATE', 'ETHABOXAM',
       'ETHALFLURALIN', 'ETHEPHON', 'ETHION', 'ETHOFUMESATE',
       'ETHOPROPHOS', 'ETOXAZOLE', 'ETRIDIAZOLE', 'FAMOXADONE',
       'FATTY ALCOHOLS', 'FENAMIDONE', 'FENAMIPHOS', 'FENARIMOL',
       'FENAZAQUIN', 'FENBUCONAZOLE', 'FENBUTATIN OXIDE', 'FENHEXAMID',
       'FENOXAPROP', 'FENOXYCARB', 'FENPROPATHRIN', 'FENPYROXIMATE',
       'FENTIN', 'FERBAM', 'FIPRONIL', 'FLAZASULFURON', 'FLONICAMID',
       'FLORASULAM', 'FLUAZIFOP', 'FLUAZINAM', 'FLUBENDIAMIDE',
       'FLUCARBAZONE', 'FLUDIOXONIL', 'FLUENSULFONE', 'FLUFENACET',
       'FLUMETRALIN', 'FLUMETSULAM', 'FLUMICLORAC', 'FLUMIOXAZIN',
       'FLUOMETURON', 'FLUOPICOLIDE', 'FLUOPYRAM', 'FLUOXASTROBIN',
       'FLUPYRADIFURONE', 'FLURIDONE', 'FLUROXYPYR', 'FLUTHIACET-METHYL',
       'FLUTOLANIL', 'FLUTRIAFOL', 'FLUVALINATE TAU', 'FLUXAPYROXAD',
       'FOLPET', 'FOMESAFEN', 'FORAMSULFURON', 'FORMETANATE', 'FOSETYL',
       'GALLEX', 'GAMMA AMINOBUTYRIC ACID', 'GARLIC JUICE',
       'GIBBERELLIC ACID', 'GLIOCLADIUM VIRENS', 'GLUFOSINATE',
       'GLYPHOSATE', 'HALAUXIFEN', 'HALOSULFURON', 'HARPIN PROTEIN',
       'HEXAZINONE', 'HEXYTHIAZOX', 'HYDRAMETHYLNON', 'HYDRATED LIME',
       'HYDROGEN PEROXIDE', 'HYMEXAZOL', 'IBA', 'IMAZALIL',
       'IMAZAMETHABENZ', 'IMAZAMOX', 'IMAZAPIC', 'IMAZAPYR', 'IMAZAQUIN',
       'IMAZETHAPYR', 'IMAZOSULFURON', 'IMIDACLOPRID', 'INDAZIFLAM',
       'INDOXACARB', 'IODOSULFURON', 'IPCONAZOLE', 'IPRODIONE',
       'ISARIA FUMOSOROSEA', 'ISOFETAMID', 'ISOXABEN', 'ISOXAFLUTOLE',
       'KAOLIN CLAY', 'KASUGAMYCIN', 'KINOPRENE', 'KRESOXIM-METHYL',
       'L-GLUTAMIC ACID', 'LACTOFEN', 'LINDANE', 'LINURON', 'MALATHION',
       'MALEIC HYDRAZIDE', 'MANCOZEB', 'MANDIPROPAMID', 'MANEB', 'MCPA',
       'MCPB', 'MECOPROP', 'MEFENOXAM', 'MEPIQUAT', 'MESOSULFURON',
       'MESOTRIONE', 'METALAXYL', 'METALDEHYDE', 'METAM',
       'METAM POTASSIUM', 'METCONAZOLE', 'METHAMIDOPHOS', 'METHIDATHION',
       'METHIOCARB', 'METHOMYL', 'METHOXYCHLOR', 'METHOXYFENOZIDE',
       'METHYL BROMIDE', 'METHYL PARATHION', 'METIRAM', 'METOLACHLOR',
       'METOLACHLOR & METOLACHLOR-S', 'METOLACHLOR-S', 'METRAFENONE',
       'METRIBUZIN', 'METSULFURON', 'MEVINPHOS', 'MSMA', 'MYCLOBUTANIL',
       'MYROTHECIUM VERRUCARIA', 'NALED', 'NAPHTHYLACETAMIDE',
       'NAPHTHYLACETIC ACID', 'NAPROPAMIDE', 'NAPTALAM', 'NEEM OIL',
       'NICOSULFURON', 'NORFLURAZON', 'NOSEMA LOCUSTAE CANN', 'NOVALURON',
       'ORTHOSULFAMURON', 'ORYZALIN', 'OXADIAZON', 'OXAMYL',
       'OXATHIAPIPROLIN', 'OXYDEMETON-METHYL', 'OXYFLUORFEN',
       'OXYTETRACYCLINE', 'PACLOBUTRAZOL', 'PAECILOMYCES LILACINUS',
       'PARAQUAT', 'PARATHION', 'PASTEURIA NISHIZAWAE', 'PELARGONIC ACID',
       'PENDIMETHALIN', 'PENFLUFEN', 'PENOXSULAM', 'PENTHIOPYRAD',
       'PERMETHRIN', 'PETROLEUM DISTILLATE', 'PETROLEUM OIL',
       'PHENMEDIPHAM', 'PHORATE', 'PHOSMET', 'PHOSPHAMIDON',
       'PHOSPHORIC ACID', 'PICLORAM', 'PICOXYSTROBIN', 'PINOLENE',
       'PINOXADEN', 'PIPERONYL BUTOXIDE', 'POLYHEDROSIS VIRUS',
       'POLYOXORIM', 'POTASSIUM BICARBONATE', 'POTASSIUM OLEATE',
       'POTASSIUM SILICATE', 'PRIMISULFURON', 'PRODIAMINE',
       'PROHEXADIONE', 'PROHYDROJASMON', 'PROMETON', 'PROMETRYN',
       'PROPAMOCARB HCL', 'PROPANIL', 'PROPARGITE', 'PROPAZINE',
       'PROPICONAZOLE', 'PROPOXUR', 'PROPOXYCARBAZONE', 'PROPYZAMIDE',
       'PROSULFURON', 'PROTHIOCONAZOLE', 'PSEUDOMONAS FLUORESCENS',
       'PYMETROZINE', 'PYRACLOSTROBIN', 'PYRAFLUFEN ETHYL',
       'PYRASULFOTOLE', 'PYRETHRINS', 'PYRIDABEN', 'PYRIMETHANIL',
       'PYRIPROXYFEN', 'PYRITHIOBAC-SODIUM', 'PYROXASULFONE',
       'PYROXSULAM', 'QUINCLORAC', 'QUINOXYFEN', 'QUINTOZENE',
       'QUIZALOFOP', 'RESMETHRIN', 'REYNOUTRIA SACHALINENSIS',
       'RIMSULFURON', 'ROTENONE', 'RYANODINE', 'SABADILLA',
       'SAFLUFENACIL', 'SEDAXANE', 'SETHOXYDIM', 'SILICATES', 'SIMAZINE',
       'SODIUM CHLORATE', 'SODIUM METABORATE', 'SPINETORAM', 'SPINOSYN',
       'SPIRODICLOFEN', 'SPIROMESIFEN', 'SPIROTETRAMAT',
       'STREPTOMYCES LYDICUS', 'STREPTOMYCIN', 'SUCROSE OCTANOATE',
       'SULFCARBAMIDE', 'SULFENTRAZONE', 'SULFOMETURON', 'SULFOSATE',
       'SULFOSULFURON', 'SULFOXAFLOR', 'SULFUR', 'SULFURIC ACID', 'TCMTB',
       'TEBUCONAZOLE', 'TEBUFENOZIDE', 'TEBUPIRIMPHOS', 'TEBUTHIURON',
       'TEFLUTHRIN', 'TEMBOTRIONE', 'TERBACIL', 'TERBUFOS', 'TERBUTRYN',
       'TETRABOROHYDRATE', 'TETRACONAZOLE', 'TETRATHIOCARBONATE',
       'THIABENDAZOLE', 'THIACLOPRID', 'THIAMETHOXAM', 'THIAZOPYR',
       'THIDIAZURON', 'THIENCARBAZONE-METHYL', 'THIFENSULFURON',
       'THIOBENCARB', 'THIODICARB', 'THIOPHANATE-METHYL', 'THIRAM',
       'TOLCLOFOS-METHYL', 'TOLFENPYRAD', 'TOPRAMEZONE', 'TRALKOXYDIM',
       'TRI-ALLATE', 'TRIADIMEFON', 'TRIADIMENOL', 'TRIASULFURON',
       'TRIBENURON METHYL', 'TRIBUFOS', 'TRICLOPYR', 'TRIFLOXYSTROBIN',
       'TRIFLOXYSULFURON', 'TRIFLUMIZOLE', 'TRIFLURALIN',
       'TRIFLUSULFURON', 'TRIFORINE', 'TRINEXAPAC', 'TRITICONAZOLE',
       'UNICONAZOLE', 'VINCLOZOLIN', 'ZETA-CYPERMETHRIN', 'ZINC', 'ZINEB',
       'ZIRAM', 'ZOXAMIDE'], dtype=object)

4. According to this dataset, what is the low estimate of total kilograms of all pesticides used across the continental US between 2013 and 2017?

In [28]:
df.EPEST_LOW_KG.sum()

2320571718.100001

5. Create a new calculated column in `df` called `EPEST_MID_KG` that represents the midpoint between the high and low pesticide estimates, `EPEST_LOW_KG` and `EPEST_HIGH_KG`. Display the a sample of the results using `.tail()`.

In [29]:
df['EPEST_MID_KG'] = (df.EPEST_HIGH_KG + df.EPEST_LOW_KG)/2
df.tail()

,COMPOUND,YEAR,STATE_FIPS_CODE,COUNTY_FIPS_CODE,EPEST_LOW_KG,EPEST_HIGH_KG,EPEST_MID_KG
2004800,ZOXAMIDE,2017,55,133,0.0,0.1,0.05
2004801,ZOXAMIDE,2017,55,135,28.2,28.2,28.20
2004802,ZOXAMIDE,2017,55,137,315.0,315.0,315.00
2004803,ZOXAMIDE,2017,55,139,0.1,3.2,1.65
2004804,ZOXAMIDE,2017,55,141,1.7,1.7,1.70

6. Sort `df` by `YEAR`, then `EPEST_MID_KG`, both in descending order and display the results.

In [30]:
df.sort_values(['YEAR', 'EPEST_MID_KG'], ascending=[False, False])

,COMPOUND,YEAR,STATE_FIPS_CODE,COUNTY_FIPS_CODE,EPEST_LOW_KG,EPEST_HIGH_KG,EPEST_MID_KG
1759528,SULFUR,2017,6,19,4370762.6,4370762.6,4370762.6
1759551,SULFUR,2017,6,77,3167766.5,3167766.5,3167766.5
1188098,METAM,2017,53,25,3068973.7,3068973.7,3068973.7
1430820,PETROLEUM OIL,2017,53,77,2369090.4,2532469.6,2450780.0
1759532,SULFUR,2017,6,29,2180839.0,2180839.0,2180839.0
...,...,...,...,...,...,...,...
2001773,ZOXAMIDE,2013,55,49,NaN,18.6,NaN
2001781,ZOXAMIDE,2013,55,65,NaN,0.2,NaN
2001800,ZOXAMIDE,2013,55,103,NaN,0.6,NaN
2001804,ZOXAMIDE,2013,55,111,NaN,0.1,NaN
2001810,ZOXAMIDE,2013,55,123,NaN,2.8,NaN

7. The `STATE_FIPS_CODE` column is a unique code for each US state, and the `COUNTY_FIPS_CODE` is a unique code for each county within a state. Together,  State and County FIPS codes uniquely identify each county in the US.

  Create a new column called `STATE_CNTY_FIPS_CODE` that concatenates `STATE_FIPS_CODE` and `COUNTY_FIPS_CODE` with a hyphen (-) in the middle. This column is a unique identifier for each US County. Check a portion of your work with `.head()`

  (State and County FIPS codes are very common in US government data. Next week, we'll learn methods for handling FIPS codes in a more robust way.)

In [39]:
df['STATE_CNTY_FIPS_CODE'] = df['STATE_FIPS_CODE'].astype(str) + '-' + df['COUNTY_FIPS_CODE'].astype(str)
df.STATE_CNTY_FIPS_CODE.head()

0     41-1
1    41-21
2    41-27
3    41-49
4    41-55
Name: STATE_CNTY_FIPS_CODE, dtype: object

8. How many unique values of `COMPOUND` are there in the dataset? (Display the result.)

In [43]:
c = df.COMPOUND.nunique()
c

448

9. How many unique values of `YEAR` are there in the dataset? (Display the result.)

In [44]:
y = df.YEAR.nunique()
y

5

10. How many unique values of `STATE_CNTY_FIPS_CODE` are there in the dataset? (Display the result.)

In [45]:
s = df.STATE_CNTY_FIPS_CODE.nunique()
s

3066

11. Multiply together the unique values of `COMPOUND`, `YEAR`, and `STATE_CNTY_FIPS_CODE` from the previous three questions and display the result.

  How does this number compare to the total number of rows in the dataset? What does this tell us about the covereage of data across these three dimensions?

In [46]:
c * y * s

6867840

There are a little over 2 million data entries (2,004,805) in this dataset. Theoretically, if we had wanted to know each unique pesticide usage in every agricultural county in the coterminus US for each year of the dataset, we'd need close to 7 million data entries (6,867,840). So we know this data doesn't completely cover all three dimensions.

Congrats! You're done with your first assignment! Be sure to got to "File" > "Save a Copy ing GitHub" to commit your work to your assignment repository.

Hopefully you can sense the possibilities and are starting to get excited about all the datasets we can explore.

Next week we'll learn how to tidy up raw data and start analyzing it.